spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lotto?characterEncoding=UTF-8
    username: root
    password:

#  jpa:
#    hibernate:
#      ddl-auto: create
server:
  servlet:
    context-path: "/api"

